Leandro.LojaVirtual.Web/Models/CarrinhoViewModel.cs
using Leandro.LojaVitural.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Leandro.LojaVirtual.Web.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }

        public string ReturnUrl { get; set; }
    }
}

Leandro.LojaVirtual.Web/Models/Paginacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Leandro.LojaVirtual.Web.Models
{
    public class Paginacao
    {
        public Int32 ItensTotal { get; set; }
        public Int32 ItensPorPagina { get; set; }
        public Int32 PaginaAtual { get; set; }
        public Int32 TotalPaginas
        {
            get
            {
                return (Int32)Math.Ceiling((decimal)ItensTotal / ItensPorPagina);                    ;

            }
        }
    }
}

Leandro.LojaVirtual.Web/Models/ProdutosViewModel.cs
using Leandro.LojaVitural.Dominio.Entidades;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Leandro.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }
    }
}

Leandro.LojaVirtual.Web/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Leandro.LojaVitural.Dominio.Repository;
using Leandro.LojaVitural.Dominio.Entidades;
using Leandro.LojaVirtual.Web.Models;

namespace Leandro.LojaVirtual.Web.Controllers
{
    public class CarrinhoController : Controller
    {

        private ProdutoRepository _repositorio;

        // GET: Carrinho
        public RedirectToRouteResult Adicionar(Int32 produtoID, string returnUrl)
        {
            _repositorio = new ProdutoRepository();

            Produto produto = _repositorio.Produtos.FirstOrDefault(x => x.ProdutoId == produtoID);

            if (produto != null)
            {
                ObterCarrinho().AdicionarItem(produto, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public Carrinho ObterCarrinho()
        {
            Carrinho carrinho = (Carrinho)Session["Carrinho"];

            if (carrinho == null)
            {
                carrinho = new Carrinho();
                Session["Carrinho"] = carrinho;
            }

            return carrinho;
        }

        public RedirectToRouteResult Remover(int produtoID, string returnUrl)
        {
            _repositorio = new ProdutoRepository(); 

            Produto produto = _repositorio.Produtos.FirstOrDefault(x => x.ProdutoId == produtoID);

            if (produto != null)
            {
                ObterCarrinho().RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = ObterCarrinho(),
                ReturnUrl = returnUrl
            });
        }

        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }
    }
}

Leandro.LojaVirtual.Web/Controllers/CategoriaController.cs
using Leandro.LojaVitural.Dominio.Entidades;
using Leandro.LojaVitural.Dominio.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Leandro.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutoRepository _repositorio;
        // GET: Categoria
        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            _repositorio = new ProdutoRepository();

            IEnumerable<string> categorias = _repositorio.Produtos.
                    Select(c => c.Categoria)
                    .Distinct()
                    .OrderBy(c => c);


            return PartialView(categorias);
        }
    }
}

Leandro.LojaVirtual.Web/Controllers/ProdutoController.cs
using Leandro.LojaVitural.Dominio.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Leandro.LojaVirtual.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutoRepository _repository;

        public ActionResult Index()
        {
            _repository = new ProdutoRepository();
            var produtos = _repository.Produtos.Take(10);

            return View(produtos);
        }
    }
}

Leandro.LojaVirtual.Web/Controllers/VitrineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Leandro.LojaVitural.Dominio.Repository;
using Leandro.LojaVirtual.Web.Models;

namespace Leandro.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutoRepository _repository;

        int produtoPorPagina = 5;


        // GET: Vitrine
        public ActionResult ListarPaginaProduto(string categoria,int pagina = 1)
        {
                _repository = new ProdutoRepository();
            ProdutosViewModel model = new ProdutosViewModel()
            {
                
                Produtos = _repository.Produtos
                                .Where(c => categoria == null || c.Categoria == categoria)
                                .OrderBy(p => p.Descricao)
                                .Skip((pagina - 1) * produtoPorPagina)
                                .Take(produtoPorPagina),

                Paginacao = new Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = produtoPorPagina,
                    ItensTotal = _repository.Produtos.Where(c => categoria == null || c.Categoria == categoria).Count()
                },

                CategoriaAtual = categoria
            };

            return View(model);
        }
    }
}

Leandro.LojaVirtual.Web/Views/Carrinho/FecharPedido.cshtml
@model Leandro.LojaVitural.Dominio.Entidades.Pedido

@{
    ViewBag.Titçe = "Leandro: Fechar Pedido";
}

<h2>Fechar o pedido</h2>

<p>Digite suas informações abaixo</p>

@using (Html.BeginForm())
{

    @Html.ValidationSummary()

    <h3> Enviar para</h3>

    <div class="form-group">
        <label> Nome do cliente:</label>
        @Html.TextBoxFor(x => x.NomeCliente, new { @class = "form-control" })
    </div>

    <h3> Dados para Entrega</h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "NomeCliente" && property.PropertyName != "EmbrulhaPresente")
        {
            <div class="form-group">
                <label> @(property.DisplayName ?? property.PropertyName)</label>

                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>Opções</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.EmbrulhaPresente)
            Embrulhar para presente ?
        </label>
    </div>

        <input class="btn btn-primary" type="submit" value="Fechar o pedido" />

}

Leandro.LojaVirtual.Web/Views/Carrinho/Index.cshtml
@model Leandro.LojaVirtual.Web.Models.CarrinhoViewModel

@{
    ViewBag.title = "Leandro : Seu carrinho";
}

<h2> Seu Carrinho</h2>

<style>
    #carrinhoTable td {
        vertical-align: middle;
    }
</style>

<table id="carrinhoTable" class="table">
    <thead>
        <tr>
            <th> Quantidade</th>
            <th> Produto</th>
            <th class="text-right">Preço</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Carrinho.ItensCarrinho)
        {
            <tr>
                <td class="text-center"> @item.Quantidade  </td>
                <td class="text-center"> @item.Produto.Nome </td>
                <td class="text-right">  @item.Produto.Preco.ToString("c") </td>
                <td class="text-right"> @((item.Quantidade * @item.Produto.Preco).ToString("c") )</td>
                <td>
                    @using (Html.BeginForm("Remover", "Carrinho"))
                    {
                        @Html.Hidden("ProdutoID", item.Produto.ProdutoId);
                        @Html.HiddenFor(x => x.ReturnUrl);
                        <input type="submit" value="Remover" class="btn btn-sm btn-warning" />

                    }
                </td>
            </tr>

        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right"> Total: </td>
            <td class="text-right"> @Model.Carrinho.ObterValorTotal().ToString("c") </td>
        </tr>
     </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continuar Comprando</a>
    @Html.ActionLink("Fechar o Pedido", "FecharPedido", "Carrinho", new { @class = "btn btn-primary" })
</div>

Leandro.LojaVirtual.Web/Views/Categoria/Menu.cshtml
@model System.Collections.Generic.IEnumerable<string>

@Html.ActionLink("Todos os Produtos", "ListarPaginaProduto", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Vitrine",
        action = "ListarPaginaProduto",
        categoria = link,
        pagina = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg" + (link == ViewBag.CategoriaSelecionada ? " btn-primary" : "")
    })
}

Leandro.LojaVirtual.Web/Views/Produto/Index.cshtml
@model IEnumerable<Leandro.LojaVitural.Dominio.Entidades.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProdutoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProdutoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProdutoId })
        </td>
    </tr>
}

</table>

Leandro.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Leandro.LojaVitural.Dominio.Entidades.Produto

<div class="well">

    <div>
        <h3><span class="pull-right label label-primary"> @Model.Preco.ToString("c") </span></h3>   
    </div>

    <h3><strong>@Model.Nome</strong></h3>

    @using (Html.BeginForm("Adicionar", "Carrinho"))
    {
        <div class="pull-right">

            @Html.HiddenFor(x => x.ProdutoId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" value="Comprar" class="btn btn-success" />
        </div>
    }
    <h3> <span class="lead">@Model.Descricao </span></h3>   
</div>  

Leandro.LojaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title = Leandro Loja Virtual</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse " role="navigation">
        <a class="navbar-brand" href="#"> Leandro Loja Virtual - Seu esporte é aqui</a>
    </div>
    <div class="row panel">
        <div id="categorias" class="row col-xs-3" style="margin-left:0px;margin-right:0px">
            @Html.Action("Menu", "Categoria")
        </div>
        <div id="produtos" class="row col-xs-8">
            @RenderBody()
        </div>
    </div>    
</body>
</html>

Leandro.LojaVirtual.Web/Views/Vitrine/ListarPaginaProduto.cshtml
@using Leandro.LojaVirtual.Web.HtmlHelpers
@model  Leandro.LojaVirtual.Web.Models.ProdutosViewModel

@foreach (var p in Model.Produtos)
{
    @Html.Partial("ProdutoDetalhes", p)
}
<div class="btn-group pull-right ">
    @Html.PageLinks(Model.Paginacao, x => Url.Action("ListarPaginaProduto", new { pagina = x, categoria = Model.CategoriaAtual }))
</div>